**NumPy Module**

NumPy is a Python library.  
NumPy is used for working with arrays.  
NumPy is short for "Numerical Python".  

**What is NumPy?**  
NumPy is a Python library used for working with arrays.  
It also has functions for working in domain of linear algebra, fourier transform, and matrices.  
NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.  
NumPy stands for Numerical Python.  

**Why Use NumPy?**  
In Python we have lists that serve the purpose of arrays, but they are slow to process.  
NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.  
The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.  
Arrays are very frequently used in data science, where speed and resources are very important.  

**Why is NumPy Faster Than Lists?**  
NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.  
This behavior is called locality of reference in computer science.  
This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

**Which Language is NumPy written in?**  
NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.  

**Where is the NumPy Codebase?**  
The source code for NumPy is located at this github repository https://github.com/numpy/numpy

**Installation of NumPy**  
If you have Python and PIP already installed on a system, then installation of NumPy is very easy.  
 
Install it using this command: 
C:\Users\Your Name>pip install numpy  

If this command fails, then use a python distribution that already has NumPy installed like, Anaconda, Spyder etc.

**Import NumPy**  
Once NumPy is installed, import it in your applications by adding the import keyword:  

import numpy  

Now NumPy is imported and ready to use. 

**NumPy as np**  
NumPy is usually imported under the np alias.  

alias: In Python alias are an alternate name for referring to the same thing.  

import numpy as np  
Now the NumPy package can be referred to as np instead of numpy.  

**Checking NumPy Version**  
The version string is stored under __version__ attribute.


In [1]:
#ExampleGet your own Python Server
import numpy
arr = numpy.array([1, 2, 3, 4, 5])  #this is the basic syntex to create an array in the numpy library
print(arr)

#Example Create an alias with the as keyword while importing: 
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

#chinhg the version of the numpy 
version_of_numpy = np.__version__
print(f"The version of the numpy is: {version_of_numpy}")

[1 2 3 4 5]
[1 2 3 4 5]
The version of the numpy is: 1.26.0


**Create a NumPy ndarray Object**  
NumPy is used to work with arrays. The array object in NumPy is called ndarray.  
We can create a NumPy ndarray object by using the array() function.  

type(): This built-in Python function tells us the type of the object passed to it. Like in above code it shows that arr is numpy.ndarray type. 

To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:  

In [2]:
array1 = np.array([8,56,48,65,25,555,25])  #here passing the list in the array() function
print(array1)
print("The type of the array1 is: ",type(array1))

#now going to create the array with passing tuple in the array() function
array2 = np.array((5,6,8,2,102,58,54))
print(f"The array2 is: {array2}")
print(type(array2))

[  8  56  48  65  25 555  25]
The type of the array1 is:  <class 'numpy.ndarray'>
The array2 is: [  5   6   8   2 102  58  54]
<class 'numpy.ndarray'>


**Dimensions in Arrays**  
A dimension in arrays is one level of array depth (nested arrays).  
nested array: are arrays that have arrays as their elements.  

**0-D Arrays**  
0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.  

**1-D Arrays**  
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.  
These are the most common and basic arrays. 

**2-D Arrays**  
An array that has 1-D arrays as its elements is called a 2-D array.  
These are often used to represent matrix or 2nd order tensors.  

NumPy has a whole sub module dedicated towards matrix operations called numpy.mat 

**3-D arrays**  
An array that has 2-D arrays (matrices) as its elements is called 3-D array.  
These are often used to represent a 3rd order tensor. 

**Check Number of Dimensions?**  
NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.  

**Higher Dimensional Arrays**  
An array can have any number of dimensions.  
When the array is created, you can define the number of dimensions by using the ndmin argument.  



In [3]:
#creating the 0-level arrays
#Create a 0-D array with value 42
arr0 = np.array(42)
print("The zero-D array is: ",arr0," and thier type is: ",type(arr0))

#Create a 1-D array containing the values 1,2,3,4,5:
arr1 = np.array([1, 2, 3, 4, 5])
print("The 1-D array is: ",arr1," and thier type is: ",type(arr1))
print()

#Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("The 2-D array is: ",arr2," and it's type is: ",type(arr2))
print()

#creating the three dimention arrays
arr3 = np.array([[[111,112,113],[121,122,123]],[[211,212,213],[221,222,223]]])
print("The 3-D array is: ",arr3," and it's type is: ",type(arr3))
print()

#Check how many dimensions the arrays have: using the keyword 'ndim'
print(arr0.ndim)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print()

#Creating the higher order arrays like 5D or 6D or 7D ..
#Create an array with 5 dimensions and verify that it has 5 dimensions:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)
'''
In this array the innermost dimension (5th dim) has 4 elements,
the 4th dim has 1 element that is the vector, 
the 3rd dim has 1 element that is the matrix with the vector, 
the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array. 
'''

The zero-D array is:  42  and thier type is:  <class 'numpy.ndarray'>
The 1-D array is:  [1 2 3 4 5]  and thier type is:  <class 'numpy.ndarray'>

The 2-D array is:  [[1 2 3]
 [4 5 6]]  and it's type is:  <class 'numpy.ndarray'>

The 3-D array is:  [[[111 112 113]
  [121 122 123]]

 [[211 212 213]
  [221 222 223]]]  and it's type is:  <class 'numpy.ndarray'>

0
1
2
3

[[[[[1 2 3 4]]]]]
number of dimensions : 5


'\nIn this array the innermost dimension (5th dim) has 4 elements,\nthe 4th dim has 1 element that is the vector, \nthe 3rd dim has 1 element that is the matrix with the vector, \nthe 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array. \n'

**NumPy Array Indexing** 

**Access Array Elements**  
Array indexing is the same as accessing an array element.  
You can access an array element by referring to its index number.  
The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.  

**Access 2-D Arrays**  
To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.  
Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.  

**Access 3-D Arrays**  
To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.  

**Negative Indexing**  
Use negative indexing to access an array from the end.

In [4]:
#deal with the 1D arrays
#Get the first element from the following array:
arr11 = np.array([1, 2, 3, 4])
print("The ele at the 0th position is: ",arr11[0])
#Get the third element from the following array:
arr11 = np.array([1, 2, 3, 4])
print("The ele at the 3rd position is: ",arr11[2])
#Get third and fourth elements from the following array and add them.
addition_of_arr11 = arr11[2]+arr11[3]
print("The additon is: ",addition_of_arr11)
print()

#deal with the 2D arrays
#Access the element on the first row, second column:
arr22 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr22[0, 1])
#Access the element on the 2nd row, 5th column:
print('5th element on 2nd row: ', arr22[1, 4])
#Access the elem on the 3rd row, 2nd column
arr22 = np.array([[1,2,3,4,5], [6,7,8,9,10],[11,12,13,14,15]])
print('2nd element on 3rd row: ', arr22[2, 1])
print()

#deal with the 3D arrays
#Access the third element of the second array of the first array: (1st)'s->(2nd)'s->(3rd element)
arr33 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr33[0, 1, 2])
''' 
arr[0, 1, 2] prints the value 6.

And this is why:

The first number represents the first dimension, which contains two arrays:
[[1, 2, 3], [4, 5, 6]]
and:
[[7, 8, 9], [10, 11, 12]]
Since we selected 0, we are left with the first array:
[[1, 2, 3], [4, 5, 6]]

The second number represents the second dimension, which also contains two arrays:
[1, 2, 3]
and:
[4, 5, 6]
Since we selected 1, we are left with the second array:
[4, 5, 6]

The third number represents the third dimension, which contains three values:
4
5
6
Since we selected 2, we end up with the third value:
6
'''
#access the 3nd elem of the first array of 2nd arrays: (2nd)'s->(1st)'s->(3rd element)
print(arr33[1,0,2])
print()

#deal with negative indexing
#Print the last element from the 2nd dim:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])
#3rd last value
print("The 3rd last value is: ",arr[-1,-3])
#2nd value at 1st array
print("The second value at the first array is: ",arr[-2,-4])

The ele at the 0th position is:  1
The ele at the 3rd position is:  3
The additon is:  7

2nd element on 1st row:  2
5th element on 2nd row:  10
2nd element on 3rd row:  12

6
9

Last element from 2nd dim:  10
The 3rd last value is:  8
The second value at the first array is:  2


**NumPy Array Slicing**

**Slicing arrays**  
Slicing in python means taking elements from one given index to another given index.  
We pass slice instead of index like this: [start:end].  
We can also define the step, like this: [start:end:step].  
If we don't pass start its considered 0  
If we don't pass end its considered length of array in that dimension  
If we don't pass step its considered 1  
Note: The result includes the start index, but excludes the end index.  

**Negative Slicing**  
Use the minus operator to refer to an index from the end:  

**STEP**  
Use the step value to determine the step of the slicing:  

In [5]:
#Slice elements from index 1 to index 5 from the following array:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])
#Slice elements from index 4 to the end of the array:
print(arr[4:]) 
#Slice elements from the beginning to index 4 (not included):
print(arr[:4])
print()

#Negative slicing
print("Slicing with the Negative index")
#Slice from the index 3 from the end to index 1 from the end:
print(arr[-3:-1])
#last to first
print(arr[:-1])
print()

#Stape parameter
print("Slicing with stape parameter")
#Return every other element from index 1 to index 5: 2 elm chhod ke 
print(arr[1:5:2])
#Return every other element from the entire array:
print(arr[::2])
print()

#Slicing in the 2D arrays
print("2D-Array Slicing")
#From the second element, slice elements from index 1 to index 4 (not included):
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1,1:4])  
#From both elements, return index 2:
print(arr[0:2,2])
#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
print(arr[0:2,1:4])


[2 3 4 5]
[5 6 7]
[1 2 3 4]

Slicing with the Negative index
[5 6]
[1 2 3 4 5 6]

Slicing with stape parameter
[2 4]
[1 3 5 7]

2D-Array Slicing
[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


**NumPy Data Types**

**Data Types in Python**  
By default Python have these data types:  
strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"  
integer - used to represent integer numbers. e.g. -1, -2, -3  
float - used to represent real numbers. e.g. 1.2, 42.42  
boolean - used to represent True or False.  
complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j  
Data Types in NumPy  
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.  

Below is a list of all data types in NumPy and the characters used to represent them.  

i - integer  
b - boolean   
u - unsigned integer   
f - float   
c - complex float   
m - timedelta    
M - datetime   
O - object   
S - string    
U - unicode string    
V - fixed chunk of memory for other type ( void )    

**Checking the Data Type of an Array**  
The NumPy array object has a property called dtype that returns the data type of the array:  

**Creating Arrays With a Defined Data Type**  
We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements:  

**What if a Value Can Not Be Converted?**  
If a type is given in which elements can't be casted then NumPy will raise a ValueError.  

ValueError: In Python ValueError is raised when the type of passed argument to a function is unexpected/incorrect.  

**Converting Data Type on Existing Arrays**  
The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.  
The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.   
The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.  

In [6]:
#Get the data type of an array object:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)
#Get the data type of an array containing strings:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr)
print(arr.dtype)

#creating the array with the define data-type
arr1 = np.array([1, 2, 3, 4], dtype='S')
print(arr1)
print(arr1.dtype)
arr2 = np.array([45,25,56,89.09,45],dtype='f')
print("arr2 data-type is: ",arr2.dtype)
arr22 = np.array([45,25,56,89.09,45],dtype='c')
print("arr2 data-type is: ",arr22.dtype)
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)

#Converting Data Type on Existing Arrays (converting the one data-type to another data-type in the numpy)
arr44 = np.array([1, 2, 3, 4], dtype='i')
arr55 = arr44.astype('f')
print(arr55)
print(arr55.dtype)

arr66 = np.array([2.39,44.90,78.8,55.45],dtype='f')
arr77 = arr66.astype('i')
print(arr77.dtype)
#Change data type from integer to boolean:
arr88 = np.array([1, 0, 3])
newarr99 = arr88.astype(bool)
print(newarr99)
print(newarr99.dtype)

int32
['apple' 'banana' 'cherry']
<U6
[b'1' b'2' b'3' b'4']
|S1
arr2 data-type is:  float32
arr2 data-type is:  |S1
[1 2 3 4]
int32
[1. 2. 3. 4.]
float32
int32
[ True False  True]
bool


In [7]:
arr22 = np.array(['a',8363,393,43,34,'b'],dtype='i')
print(arr2)
print(arr22.dtype)

ValueError: invalid literal for int() with base 10: 'a'

**NumPy Array Copy vs View**

**The Difference Between Copy and View**  
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.  
The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.  
The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.  

**Check if Array Owns its Data**  
As mentioned above, copies owns the data, and views does not own the data, but how can we check this?  
Every NumPy array has the attribute base that returns None if the array owns the data.  
Otherwise, the base  attribute refers to the original object.



In [ ]:
#Make a copy, change the original array, and display both arrays:
#if you make an array and copy thats array in the other variable and after copy you doing changes in the that array, then that new copied value not affexted only changes valid in the array
#The copy SHOULD NOT be affected by the changes made to the original array.
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print("The array element is: ",arr)
print("The copy elements is: ",x)
print()

#Make a view, change the original array, and display both arrays:
#The view SHOULD be affected by the changes made to the original array.
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
print("The array element is: ",arr)
print("The copy elements is: ",x)
print()

#'base' attribute
#Print the value of the base attribute to check if an array owns it's data or not:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)
#The copy returns None.
#The view returns the original array.
#becouse view()-> don't owns the data just view the where we getting refrence hece changese eill affected changes and copy()-> owns the data hase dose not affected changes

The array element is:  [42  2  3  4  5]
The copy elements is:  [1 2 3 4 5]

The array element is:  [42  2  3  4  5]
The copy elements is:  [42  2  3  4  5]

None
[1 2 3 4 5]


**NumPy Array Shape**

**Shape of an Array**  
The shape of an array is the number of elements in each dimension.  

**Get the Shape of an Array**  
NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.  

In [ ]:
#just shape is return the size of the array at the tuple if array is multidimention the it return each dimentions sizes
arr = np.array([974.5,498.9,3444.0])
print(arr.shape)

#Print the shape of a 2-D array:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)
'''The example above returns (2, 4), which means that the array has 2 dimensions, where the first dimension has 2 elements and the second has 4.'''

#Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:
arr = np.array([1, 2, 3, 4], ndmin=5)
print('shape of array :', arr.shape)



(3,)
(2, 4)
shape of array : (1, 1, 1, 1, 4)


**NumPy Array Reshaping**

**Reshaping arrays**  
Reshaping means changing the shape of an array.  
The shape of an array is the number of elements in each dimension.  
By reshaping we can add or remove dimensions or change number of elements in each dimension.  

**Can We Reshape Into any Shape?**  
Yes, as long as the elements required for reshaping are equal in both shapes.  
We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.

**Unknown Dimension**  
You are allowed to have one "unknown" dimension.  
Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.  
Pass -1 as the value, and NumPy will calculate this number for you.   

**Flattening the arrays**  
Flattening array means converting a multidimensional array into a 1D array.  
We can use reshape(-1) to do this.  
Note: There are a lot of functions for changing the shapes of arrays in numpy flatten, ravel and also for rearranging the elements rot90, flip, fliplr, flipud etc. These fall under Intermediate to Advanced section of numpy. 

In [ ]:
#Reshape From 1-D to 2-D
#Convert the following 1-D array with 12 elements into a 2-D array.
#The outermost dimension will have 4 arrays, each with 3 elements:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)
print()

#Reshape From 1-D to 3-D
#Convert the following 1-D array with 12 elements into a 3-D array.
#The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)
print()

#Returns Copy or View?
#Check if the returned array is a copy or a view:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4).base)
print()
#The example above returns the original array, so it is a view.

#converting into the unknown dimentions
#Convert 1D array with 8 elements to 3D array with 2x2 elements:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)
print()
#Note: We can not pass -1 to more than one dimension.

#Flattening the arrays
#Convert the array into a 1D array:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)
''' 
Note: There are a lot of functions for changing the shapes of arrays in numpy flatten,
ravel and also for rearranging the elements rot90, flip, fliplr, flipud etc. These fall under Intermediate to Advanced section of numpy.
'''

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

[1 2 3 4 5 6 7 8]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

[1 2 3 4 5 6]


In [ ]:
#Try converting 1D array with 8 elements to a 2D array with 3 elements in each dimension (will raise an error):
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8,9])
newarr = arr.reshape(3, 3)
print(newarr)

ValueError: cannot reshape array of size 8 into shape (3,3)

**NumPy Array Iterating**

**Iterating Arrays**  
Iterating means going through elements one by one.  
As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.  
If we iterate on a 1-D array it will go through each element one by one.  

**Iterating 2-D Arrays**  
In a 2-D array it will go through all the rows.

**Iterating 3-D Arrays**  
In a 3-D array it will go through all the 2-D arrays.  

**Iterating Arrays Using nditer()**  
The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.  

Iterating on Each Scalar Element  
In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.  

**Iterating Array With Different Data Types**  
We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.  
NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].  

**Iterating With Different Step Size**  
We can use filtering and followed by iteration.  

**Enumerated Iteration Using ndenumerate()**  
Enumeration means mentioning sequence number of somethings one by one.  
Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

In [ ]:
import numpy as np
#Iterate on the elements of the following 1-D array:
print("For the 1D array")
arr = np.array([1, 2, 3])
for x in arr:
  print(x)
print("---------------------------------")

#Iterate on the elements of the following 2-D array:
print("For the 2D array")
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  print(x)
print("---------------------------------")
#Iterate on each scalar element of the 2-D array:
print("Each element in the 2D arrays.")
for x in arr:
  for y in x:
    print(y)
print("---------------------------------")

#Iterate on the elements of the following 3-D array:
print("For the 3D arrays")
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  print(x)
print("---------------------------------")
#iterating the 3D array in the rows 
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  for y in x:
    print(y)
print("---------------------------------")
#itretionf the individual elements of the arrays
for x in arr:
  for y in x:
    for z in y:
      print(z)


For the 1D array
1
2
3
---------------------------------
For the 2D array
[1 2 3]
[4 5 6]
---------------------------------
Each element in the 2D arrays.
1
2
3
4
5
6
---------------------------------
For the 3D arrays
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
---------------------------------
[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]
---------------------------------
1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
#using the 'nditer()' functions
import numpy as np
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
  print(x)
print("-------------------------------")
#using the array with the diffrent datatype
arr = np.array([1, 2, 3])
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)
print("-------------------------------")
#Iterating With Different Step Size
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr[:, ::2]):
  print(x)
print("-------------------------------")
#Enumerated Iteration Using ndenumerate()
arr = np.array([1, 2, 3])
for idx, x in np.ndenumerate(arr):
  print(idx, x)
print("-------------------------------")
#Enumerate on following 2D array's elements:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for idx, x in np.ndenumerate(arr):
  print(idx, x)


1
2
3
4
5
6
7
8
-------------------------------
b'1'
b'2'
b'3'
-------------------------------
1
3
5
7
-------------------------------
(0,) 1
(1,) 2
(2,) 3
-------------------------------
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


**NumPy Joining Array**

**Joining NumPy Arrays**  
Joining means putting contents of two or more arrays in a single array.  
In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.  
We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

**Joining Arrays Using Stack Functions**  
Stacking is same as concatenation, the only difference is that stacking is done along a new axis.  
We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.  
We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.  

**Stacking Along Rows**  
NumPy provides a helper function: hstack() to stack along rows.  

**Stacking Along Columns**  
NumPy provides a helper function: vstack()  to stack along columns.  

**Stacking Along Height (depth)**  
NumPy provides a helper function: dstack() to stack along height, which is the same as depth.

In [ ]:
#Join two arrays
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
newarr = np.concatenate((arr1,arr2))
print(newarr)
#Join two 2-D arrays along rows (axis=1):
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

#joining the arrays using the stack methods
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)
#Stacking Along Rows
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)
#Stacking Along Columns
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)
#Stacking Along Height (depth)
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]
[[1 2 5 6]
 [3 4 7 8]]
[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 4]
  [2 5]
  [3 6]]]


**NumPy Splitting Array** 

**Splitting NumPy Arrays**  
Splitting is reverse operation of Joining.  
Joining merges multiple arrays into one and Splitting breaks one array into multiple.  
We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.  
Note: The return value is a list containing three arrays.  
If the array has less elements than required, it will adjust from the end accordingly.  
Note: We also have the method split() available but it will not adjust the elements when elements are less in source array for splitting like in example above, array_split() worked properly but split() would fail.  

**Split Into Arrays**  
The return value of the array_split() method is an array containing each of the split as an array.  
If you split an array into 3 arrays, you can access them from the result just like any array element: 

**Splitting 2-D Arrays**  
Use the same syntax when splitting 2-D arrays.  
Use the array_split() method, pass in the array you want to split and the number of splits you want to do.  

An alternate solution is using hsplit() opposite of hstack()


In [ ]:
#Split the array in 3 parts:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)
#Split the array in 4 parts:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 4)
print(newarr)
#Access the splitted arrays:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr[0])
print(newarr[1])
print(newarr[2])

#Splitting 2-D Arrays
#Split the 2-D array into three 2-D arrays.
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)
#access the sprate arrays
print(newarr[0])
print(newarr[1])
print(newarr[2])

#Use the hsplit() method to split the 2-D array into three 2-D arrays along rows.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.hsplit(arr, 3)
print(newarr)
#Note: Similar alternates to vstack() and dstack() are available as vsplit() and dsplit().

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5]), array([6])]
[1 2]
[3 4]
[5 6]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 9 10]
 [11 12]]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


**NumPy Searching Arrays** 

**Searching Arrays**  
You can search an array for a certain value, and return the indexes that get a match.  
To search an array, use the where() method.  

**Search Sorted**  
There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.  
The searchsorted() method is assumed to be used on sorted arrays.  

The method starts the search from the left and returns the first index where the number 7 is no longer larger than the next value.  

**Search From the Right Side**  
By default the left most index is returned, but we can give side='right' to return the right most index instead.  

**Multiple Values**  
To search for more than one value, use an array with the specified values.

In [ ]:
#Find the indexes where the value is 4:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)
#Find the indexes where the values are even:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)
print(x)
#Find the indexes where the values are odd:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 1)
print(x)

#searchsorted() method
#Find the indexes where the value 7 should be inserted:
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)
print(x)
#Find the indexes where the value 7 should be inserted, starting from the right:
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7, side='right')
print(x)
#Multiple Values
#Find the indexes where the values 2, 4, and 6 should be inserted:
arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6])
print(x)
#The return value is an array: [1 2 3] containing the three indexes where 2, 4, 6 would be inserted in the original array to maintain the order.
#searching the more then one value
arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [1,5,7])
print(x)


(array([3, 5, 6], dtype=int64),)
(array([1, 3, 5, 7], dtype=int64),)
(array([0, 2, 4, 6], dtype=int64),)
1
2
[1 2 3]
[0 2 3]


**NumPy Sorting Arrays**

**Sorting Arrays** 
Sorting means putting elements in an ordered sequence.  
Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.  
The NumPy ndarray object has a function called sort(), that will sort a specified array.  
Note: This method returns a copy of the array, leaving the original array unchanged.  

**Sorting a 2-D Array**  
If you use the sort() method on a 2-D array, both arrays will be sorted:

In [ ]:
#Sort the array:
import numpy as np
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))
#You can also sort arrays of strings, or any other data type:
#Sort the array alphabetically:
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))
#Sort a boolean array:
arr = np.array([True, False, True])
print(np.sort(arr))

#Sort a 2-D array:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))
arr1 = np.sort(arr)
print(arr1[0]," & ",arr1[1])

[0 1 2 3]
['apple' 'banana' 'cherry']
[False  True  True]
[[2 3 4]
 [0 1 5]]
[2 3 4]  &  [0 1 5]


**NumPy Filter Array**

**Filtering Arrays**  
Getting some elements out of an existing array and creating a new array out of them is called filtering.  
In NumPy, you filter an array using a boolean index list.  
A boolean index list is a list of booleans corresponding to indexes in the array.  
If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.  

**Creating Filter Directly From Array**  
The above example is quite a common task in NumPy and NumPy provides a nice way to tackle it.  
We can directly substitute the array instead of the iterable variable in our condition and it will work just as we expect it to.  

In [ ]:
#Create an array from the elements on index 0 and 2:
import numpy as np
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]    #here is true at the index 0 & 3 so only 41 and 43 will present in the newarr
newarr = arr[x]
print(newarr)
#The example above will return [41, 43], why?
#Because the new array contains only the values where the filter array had the value True, in this case, index 0 and 2.

#Create a filter array that will return only values higher than 42:
arr = np.array([41, 42, 43, 44,57,5,28,49,34,1003])
filter_arr = []
for arrElemet in arr:
    if arrElemet>42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
print(filter_arr)
newarr = arr[filter_arr]
print(newarr)
print("-------------------------------------------------")

#Create a filter array that will return only even elements from the original array:
arr = np.array([1, 2, 3, 4, 5, 6, 7,8,9,10,11,12,13,14,15,16])
# Create an empty list
even_filter_arr = []
for elemetNo in arr:
    if elemetNo%2 == 0:
        even_filter_arr.append(True)
    else:
        even_filter_arr.append(False)
print(filter_arr)
newarrEven = arr[even_filter_arr]
print(newarrEven) 
print("-------------------------------------------------")

#Creating Filter Directly From Array
#Create a filter array that will return only values higher than 42:
arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)
print("-------------------------------------------------")
#Create a filter array that will return only even elements from the original array:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
filter_arr = arr % 2 == 0
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[41 43]
[False, False, True, True, True, False, False, True, False, True]
[  43   44   57   49 1003]
-------------------------------------------------
[False, False, True, True, True, False, False, True, False, True]
[ 2  4  6  8 10 12 14 16]
-------------------------------------------------
[False False  True  True]
[43 44]
-------------------------------------------------
[False  True False  True False  True False]
[2 4 6]
